<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class ProductosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('alp_productos')->insert([
            ['nombre_producto' => 'Leche Entera','referencia_producto' => 'LECH001','referencia_producto_sap' => '3534534534','descripcion_corta' => 'Leche entera Alpina 1Lt','descripcion_larga' => 'Leche entera Alpina 1Lt caracteristicas tal y tal','imagen_producto' => '1Zizrmiw27.jpeg','seo_titulo' => 'Leche Entera','seo_descripcion' => 'Leche entera 1ltr','slug' => 'leche-entera','id_categoria_default' => 1,'id_marca' => 1,'id_user' => 1,'id_impuesto' => 1,'pum' => 333.00,'precio_base' => 1000.00,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['nombre_producto' => 'Leche Entera2','referencia_producto' => 'LECH002','referencia_producto_sap' => '3534534222','descripcion_corta' => 'Leche entera Alpina 1Lt','descripcion_larga' => 'Leche entera Alpina 1Lt caracteristicas tal y tal','imagen_producto' => '1Zizrmiw27.jpeg','seo_titulo' => 'Leche Entera','seo_descripcion' => 'Leche entera 1ltr','slug' => 'leche-entera2','id_categoria_default' => 1,'id_marca' => 1,'id_user' => 1,'id_impuesto' => 1,'pum' => 333.00,'precio_base' => 1000.00,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['nombre_producto' => 'Leche Entera3','referencia_producto' => 'LECH002','referencia_producto_sap' => '3534534222','descripcion_corta' => 'Leche entera Alpina 1Lt','descripcion_larga' => 'Leche entera Alpina 1Lt caracteristicas tal y tal','imagen_producto' => '1Zizrmiw27.jpeg','seo_titulo' => 'Leche Entera','seo_descripcion' => 'Leche entera 1ltr','slug' => 'leche-entera3','id_categoria_default' => 1,'id_marca' => 1,'id_user' => 1,'id_impuesto' => 1,'pum' => 333.00,'precio_base' => 1000.00,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['nombre_producto' => 'Leche Entera4','referencia_producto' => 'LECH002','referencia_producto_sap' => '3534534222','descripcion_corta' => 'Leche entera Alpina 1Lt','descripcion_larga' => 'Leche entera Alpina 1Lt caracteristicas tal y tal','imagen_producto' => '1Zizrmiw27.jpeg','seo_titulo' => 'Leche Entera','seo_descripcion' => 'Leche entera 1ltr','slug' => 'leche-entera4','id_categoria_default' => 1,'id_marca' => 1,'id_user' => 1,'id_impuesto' => 1,'pum' => 333.00,'precio_base' => 1000.00,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['nombre_producto' => 'Leche Entera5','referencia_producto' => 'LECH002','referencia_producto_sap' => '3534534222','descripcion_corta' => 'Leche entera Alpina 1Lt','descripcion_larga' => 'Leche entera Alpina 1Lt caracteristicas tal y tal','imagen_producto' => '1Zizrmiw27.jpeg','seo_titulo' => 'Leche Entera','seo_descripcion' => 'Leche entera 1ltr','slug' => 'leche-entera5','id_categoria_default' => 1,'id_marca' => 1,'id_user' => 1,'id_impuesto' => 1,'pum' => 333.00,'precio_base' => 1000.00,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['nombre_producto' => 'Leche Entera6','referencia_producto' => 'LECH002','referencia_producto_sap' => '3534534222','descripcion_corta' => 'Leche entera Alpina 1Lt','descripcion_larga' => 'Leche entera Alpina 1Lt caracteristicas tal y tal','imagen_producto' => '1Zizrmiw27.jpeg','seo_titulo' => 'Leche Entera','seo_descripcion' => 'Leche entera 1ltr','slug' => 'leche-entera6','id_categoria_default' => 1,'id_marca' => 1,'id_user' => 1,'id_impuesto' => 1,'pum' => 333.00,'precio_base' => 1000.00,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['nombre_producto' => 'Leche Entera7','referencia_producto' => 'LECH002','referencia_producto_sap' => '3534534222','descripcion_corta' => 'Leche entera Alpina 1Lt','descripcion_larga' => 'Leche entera Alpina 1Lt caracteristicas tal y tal','imagen_producto' => '1Zizrmiw27.jpeg','seo_titulo' => 'Leche Entera','seo_descripcion' => 'Leche entera 1ltr','slug' => 'leche-entera7','id_categoria_default' => 1,'id_marca' => 1,'id_user' => 1,'id_impuesto' => 1,'pum' => 333.00,'precio_base' => 1000.00,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['nombre_producto' => 'Leche Entera8','referencia_producto' => 'LECH002','referencia_producto_sap' => '3534534222','descripcion_corta' => 'Leche entera Alpina 1Lt','descripcion_larga' => 'Leche entera Alpina 1Lt caracteristicas tal y tal','imagen_producto' => '1Zizrmiw27.jpeg','seo_titulo' => 'Leche Entera','seo_descripcion' => 'Leche entera 1ltr','slug' => 'leche-entera8','id_categoria_default' => 1,'id_marca' => 1,'id_user' => 1,'id_impuesto' => 1,'pum' => 333.00,'precio_base' => 1000.00,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['nombre_producto' => 'Leche Entera9','referencia_producto' => 'LECH002','referencia_producto_sap' => '3534534222','descripcion_corta' => 'Leche entera Alpina 1Lt','descripcion_larga' => 'Leche entera Alpina 1Lt caracteristicas tal y tal','imagen_producto' => '1Zizrmiw27.jpeg','seo_titulo' => 'Leche Entera','seo_descripcion' => 'Leche entera 1ltr','slug' => 'leche-entera9','id_categoria_default' => 1,'id_marca' => 1,'id_user' => 1,'id_impuesto' => 1,'pum' => 333.00,'precio_base' => 1000.00,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['nombre_producto' => 'Leche Entera10','referencia_producto' => 'LECH002','referencia_producto_sap' => '3534534222','descripcion_corta' => 'Leche entera Alpina 1Lt','descripcion_larga' => 'Leche entera Alpina 1Lt caracteristicas tal y tal','imagen_producto' => '1Zizrmiw27.jpeg','seo_titulo' => 'Leche Entera','seo_descripcion' => 'Leche entera 1ltr','slug' => 'leche-entera10','id_categoria_default' => 1,'id_marca' => 1,'id_user' => 1,'id_impuesto' => 1,'pum' => 333.00,'precio_base' => 1000.00,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['nombre_producto' => 'Leche Entera11','referencia_producto' => 'LECH002','referencia_producto_sap' => '3534534222','descripcion_corta' => 'Leche entera Alpina 1Lt','descripcion_larga' => 'Leche entera Alpina 1Lt caracteristicas tal y tal','imagen_producto' => '1Zizrmiw27.jpeg','seo_titulo' => 'Leche Entera','seo_descripcion' => 'Leche entera 1ltr','slug' => 'leche-entera11','id_categoria_default' => 1,'id_marca' => 1,'id_user' => 1,'id_impuesto' => 1,'pum' => 333.00,'precio_base' => 1000.00,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['nombre_producto' => 'Leche Entera12','referencia_producto' => 'LECH002','referencia_producto_sap' => '3534534222','descripcion_corta' => 'Leche entera Alpina 1Lt','descripcion_larga' => 'Leche entera Alpina 1Lt caracteristicas tal y tal','imagen_producto' => '1Zizrmiw27.jpeg','seo_titulo' => 'Leche Entera','seo_descripcion' => 'Leche entera 1ltr','slug' => 'leche-entera12','id_categoria_default' => 1,'id_marca' => 1,'id_user' => 1,'id_impuesto' => 1,'pum' => 333.00,'precio_base' => 1000.00,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ]);

    }
}
