<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class ProductosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('alp_productos')->insert([
            ['nombre_producto' => 'CREMA DE LECHE FINESSE CAJA 200 GR','referencia_producto' => 'LECH001','referencia_producto_sap' => '3534534534','descripcion_corta' => 'La Crema de Leche Finesse es una crema de leche semientera ultrapasteurizada. Es reducida en grasa, ya que contiene 50% menos grasa con relación a la crema de leche entera y aporta solamente 25 Calorías por porción de 15 mililitros.','descripcion_larga' => 'La crema de leche Finesse es un producto ultrapasteurizado, por tanto no requiere refrigeración antes de abrir. Se caracteriza por su versatilidad, ya que puede ser utilizada tanto en preparaciones de sal como también en postres.Pruébala para dar cuerpo y textura a preparaciones como salsas y sopas o como ingrediente de tortas y postres.Encuentra Crema de Leche Finesse en presentación de caja tetrapak de 200 mililitros.','imagen_producto' => '1cctbMfNFG.jpeg','seo_titulo' => 'Leche Entera','seo_descripcion' => 'Leche entera 1ltr','slug' => 'leche-entera','id_categoria_default' => 1,'id_marca' => 1,'id_user' => 1,'id_impuesto' => 1,'pum' => 333.00,'precio_base' => 3100.00,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['nombre_producto' => 'Leche Entera2','referencia_producto' => 'LECH002','referencia_producto_sap' => '3534534222','descripcion_corta' => 'Leche entera Alpina 1Lt','descripcion_larga' => 'Leche entera Alpina 1Lt caracteristicas tal y tal','imagen_producto' => '1Zizrmiw27.jpeg','seo_titulo' => 'Leche Entera','seo_descripcion' => 'Leche entera 1ltr','slug' => 'leche-entera2','id_categoria_default' => 1,'id_marca' => 1,'id_user' => 1,'id_impuesto' => 1,'pum' => 333.00,'precio_base' => 1000.00,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['nombre_producto' => 'Leche Entera3','referencia_producto' => 'LECH002','referencia_producto_sap' => '3534534222','descripcion_corta' => 'Leche entera Alpina 1Lt','descripcion_larga' => 'Leche entera Alpina 1Lt caracteristicas tal y tal','imagen_producto' => '1Zizrmiw27.jpeg','seo_titulo' => 'Leche Entera','seo_descripcion' => 'Leche entera 1ltr','slug' => 'leche-entera3','id_categoria_default' => 1,'id_marca' => 1,'id_user' => 1,'id_impuesto' => 1,'pum' => 333.00,'precio_base' => 1000.00,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['nombre_producto' => 'Leche Entera4','referencia_producto' => 'LECH002','referencia_producto_sap' => '3534534222','descripcion_corta' => 'Leche entera Alpina 1Lt','descripcion_larga' => 'Leche entera Alpina 1Lt caracteristicas tal y tal','imagen_producto' => '1Zizrmiw27.jpeg','seo_titulo' => 'Leche Entera','seo_descripcion' => 'Leche entera 1ltr','slug' => 'leche-entera4','id_categoria_default' => 1,'id_marca' => 1,'id_user' => 1,'id_impuesto' => 1,'pum' => 333.00,'precio_base' => 1000.00,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['nombre_producto' => 'Leche Entera5','referencia_producto' => 'LECH002','referencia_producto_sap' => '3534534222','descripcion_corta' => 'Leche entera Alpina 1Lt','descripcion_larga' => 'Leche entera Alpina 1Lt caracteristicas tal y tal','imagen_producto' => '1Zizrmiw27.jpeg','seo_titulo' => 'Leche Entera','seo_descripcion' => 'Leche entera 1ltr','slug' => 'leche-entera5','id_categoria_default' => 1,'id_marca' => 1,'id_user' => 1,'id_impuesto' => 1,'pum' => 333.00,'precio_base' => 1000.00,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['nombre_producto' => 'Leche Entera6','referencia_producto' => 'LECH002','referencia_producto_sap' => '3534534222','descripcion_corta' => 'Leche entera Alpina 1Lt','descripcion_larga' => 'Leche entera Alpina 1Lt caracteristicas tal y tal','imagen_producto' => '1Zizrmiw27.jpeg','seo_titulo' => 'Leche Entera','seo_descripcion' => 'Leche entera 1ltr','slug' => 'leche-entera6','id_categoria_default' => 1,'id_marca' => 1,'id_user' => 1,'id_impuesto' => 1,'pum' => 333.00,'precio_base' => 1000.00,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['nombre_producto' => 'Leche Entera7','referencia_producto' => 'LECH002','referencia_producto_sap' => '3534534222','descripcion_corta' => 'Leche entera Alpina 1Lt','descripcion_larga' => 'Leche entera Alpina 1Lt caracteristicas tal y tal','imagen_producto' => '1Zizrmiw27.jpeg','seo_titulo' => 'Leche Entera','seo_descripcion' => 'Leche entera 1ltr','slug' => 'leche-entera7','id_categoria_default' => 1,'id_marca' => 1,'id_user' => 1,'id_impuesto' => 1,'pum' => 333.00,'precio_base' => 1000.00,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['nombre_producto' => 'Leche Entera8','referencia_producto' => 'LECH002','referencia_producto_sap' => '3534534222','descripcion_corta' => 'Leche entera Alpina 1Lt','descripcion_larga' => 'Leche entera Alpina 1Lt caracteristicas tal y tal','imagen_producto' => '1Zizrmiw27.jpeg','seo_titulo' => 'Leche Entera','seo_descripcion' => 'Leche entera 1ltr','slug' => 'leche-entera8','id_categoria_default' => 1,'id_marca' => 1,'id_user' => 1,'id_impuesto' => 1,'pum' => 333.00,'precio_base' => 1000.00,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['nombre_producto' => 'Leche Entera9','referencia_producto' => 'LECH002','referencia_producto_sap' => '3534534222','descripcion_corta' => 'Leche entera Alpina 1Lt','descripcion_larga' => 'Leche entera Alpina 1Lt caracteristicas tal y tal','imagen_producto' => '1Zizrmiw27.jpeg','seo_titulo' => 'Leche Entera','seo_descripcion' => 'Leche entera 1ltr','slug' => 'leche-entera9','id_categoria_default' => 1,'id_marca' => 1,'id_user' => 1,'id_impuesto' => 1,'pum' => 333.00,'precio_base' => 1000.00,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['nombre_producto' => 'Leche Entera10','referencia_producto' => 'LECH002','referencia_producto_sap' => '3534534222','descripcion_corta' => 'Leche entera Alpina 1Lt','descripcion_larga' => 'Leche entera Alpina 1Lt caracteristicas tal y tal','imagen_producto' => '1Zizrmiw27.jpeg','seo_titulo' => 'Leche Entera','seo_descripcion' => 'Leche entera 1ltr','slug' => 'leche-entera10','id_categoria_default' => 1,'id_marca' => 1,'id_user' => 1,'id_impuesto' => 1,'pum' => 333.00,'precio_base' => 1000.00,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['nombre_producto' => 'Leche Entera11','referencia_producto' => 'LECH002','referencia_producto_sap' => '3534534222','descripcion_corta' => 'Leche entera Alpina 1Lt','descripcion_larga' => 'Leche entera Alpina 1Lt caracteristicas tal y tal','imagen_producto' => '1Zizrmiw27.jpeg','seo_titulo' => 'Leche Entera','seo_descripcion' => 'Leche entera 1ltr','slug' => 'leche-entera11','id_categoria_default' => 1,'id_marca' => 1,'id_user' => 1,'id_impuesto' => 1,'pum' => 333.00,'precio_base' => 1000.00,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['nombre_producto' => 'Leche Entera12','referencia_producto' => 'LECH002','referencia_producto_sap' => '3534534222','descripcion_corta' => 'Leche entera Alpina 1Lt','descripcion_larga' => 'Leche entera Alpina 1Lt caracteristicas tal y tal','imagen_producto' => '1Zizrmiw27.jpeg','seo_titulo' => 'Leche Entera','seo_descripcion' => 'Leche entera 1ltr','slug' => 'leche-entera12','id_categoria_default' => 1,'id_marca' => 1,'id_user' => 1,'id_impuesto' => 1,'pum' => 333.00,'precio_base' => 1000.00,'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ]);

    }
}
