<?php

/* custom routes generated by CRUD */


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('productos', ['as'=> 'productos.index', 'uses' => 'admin\AlpProductosController@index']);

Route::post('productos', ['as'=> 'productos.store', 'uses' => 'admin\AlpProductosController@store']);

Route::get('productos/create', ['as'=> 'productos.create', 'uses' => 'admin\AlpProductosController@create']);
Route::put('productos/{alpProductos}', ['as'=> 'alpProductos.update', 'uses' => 'AlpProductosController@update']);
Route::patch('productos/{alpProductos}', ['as'=> 'alpProductos.update', 'uses' => 'AlpProductosController@update']);
Route::get('alpProductos/{id}/delete', array('as' => 'alpProductos.delete', 'uses' => 'AlpProductosController@getDelete'));
Route::get('alpProductos/{id}/confirm-delete', array('as' => 'alpProductos.confirm-delete', 'uses' => 'AlpProductosController@getModalDelete'));
Route::get('alpProductos/{alpProductos}', ['as'=> 'alpProductos.show', 'uses' => 'AlpProductosController@show']);
Route::get('alpProductos/{alpProductos}/edit', ['as'=> 'alpProductos.edit', 'uses' => 'AlpProductosController@edit']);

});

